In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
type(l)

list

In [4]:
a = np.array(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
a1 = np.array([[1,2,3], [4,5,6]])

In [7]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a2 = np.array([[[1,2,3], [4,5,6]]])

In [9]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [10]:
a.ndim

1

In [11]:
a1.ndim

2

In [12]:
a2.ndim

3

In [13]:
a3 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [14]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [15]:
a3.ndim

3

In [16]:
l = [1,2,3,4]

In [17]:
a = np.asarray(l)

In [18]:
m = np.matrix(l)

In [19]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [20]:
a1 = a

In [21]:
a[0]= 10

In [22]:
a

array([10,  2,  3,  4])

In [23]:
a1

array([10,  2,  3,  4])

In [24]:
a1[3] = 40

In [25]:
a

array([10,  2,  3, 40])

In [26]:
a2 = np.copy(a)

In [27]:
a2

array([10,  2,  3, 40])

# Range Function

In [28]:
import numpy as np

In [29]:
range(10)

range(0, 10)

In [30]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [38]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [39]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [40]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [41]:
np.linspace(1,5,20, retstep=True)

(array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367)

In [44]:
np.logspace(1,10)

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

In [45]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [46]:
np.zeros(4)

array([0., 0., 0., 0.])

In [47]:
np.zeros((3,5,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [48]:
np.ones(3)

array([1., 1., 1.])

In [50]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [51]:
np.ones((3,6,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [52]:
np.empty((2,3))

array([[5.04095165e-310, 0.00000000e+000, 6.85524019e-310],
       [6.85524019e-310, 9.82391603e+252, 6.85519444e-310]])

In [57]:
a = np.eye(4)

In [58]:
a.shape

(4, 4)

In [59]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
a.ndim

2

In [71]:
a1 = np.random.randn(3,5)

In [72]:
a1

array([[-0.61587601, -0.87748152, -0.2263699 ,  0.25441823, -1.37966613],
       [-0.53095778,  0.08204258, -0.76672615,  1.23606454,  1.61429875],
       [ 0.45857651, -0.97382094,  0.97784183, -0.68301917,  0.20882672]])

In [73]:
import pandas as pd

In [74]:
pd.DataFrame(a1)

0         1         2         3         4
0 -0.615876 -0.877482 -0.226370  0.254418 -1.379666
1 -0.530958  0.082043 -0.766726  1.236065  1.614299
2  0.458577 -0.973821  0.977842 -0.683019  0.208827

In [79]:
a1

array([[-0.61587601, -0.87748152, -0.2263699 ,  0.25441823, -1.37966613],
       [-0.53095778,  0.08204258, -0.76672615,  1.23606454,  1.61429875],
       [ 0.45857651, -0.97382094,  0.97784183, -0.68301917,  0.20882672]])

In [80]:
a1[1][1]

0.08204258032479765

In [81]:
a1[0:1,0:2]

array([[-0.61587601, -0.87748152]])

In [83]:
a1[[1,2],3]

array([ 1.23606454, -0.68301917])

In [89]:
m1 = np.random.randint(1,3, (3,3))

In [90]:
m2 = np.random.randint(2,4, (3,3))

In [91]:
m2

array([[3, 3, 2],
       [3, 2, 3],
       [3, 2, 3]])

In [92]:
m1*m2

array([[6, 3, 4],
       [6, 2, 6],
       [6, 2, 3]])

In [93]:
# matrix multiplication

m1@m2

array([[15, 12, 13],
       [15, 12, 13],
       [12, 10, 10]])

In [95]:
m1

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [96]:
pow(m1,4)

# power of matrix

array([[16,  1, 16],
       [16,  1, 16],
       [16,  1,  1]])

In [100]:
# power of matrix
m1**2

array([[4, 1, 4],
       [4, 1, 4],
       [4, 1, 1]])

In [97]:
np.sqrt(m1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ]])

In [98]:
np.log10(m1)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.     ]])

In [99]:
#exponential fucntion

np.exp(m1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])